--external item descriptions
if EID then
	EID:addCollectible(Isaac.GetItemIdByName("Golden Idol"), "#The player has a 50% chance of receiving a fading nickel when a room is cleared#Getting damage causes the player to lose half their money, dropping some of it on the ground as fading coins.#When the player is holding money, damage is always 1 full heart", "Golden Idol", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Gun that can kill the Past"), "#Removes the oldest {{Collectible}}item from your inventory, including quest items like the Key Pieces#3 choice pedestals appear#The new {{Collectible}}items are from the same pools as the one you lost. It can be used 3 times.", "Gun that can Kill the Past", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName(" Gun that can kill the Past "), "#Removes the oldest {{Collectible}}item from your inventory, including quest items like the Key Pieces#3 choice pedestals appear#The new {{Collectible}}items are from the same pools as the one you lost. It can be used 3 times.", "Gun that can Kill the Past", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("  Gun that can kill the Past  "), "#Removes the oldest {{Collectible}}item from your inventory, including quest items like the Key Pieces#3 choice pedestals appear#The new {{Collectible}}items are from the same pools as the one you lost. It can be used 3 times.", "Gun that can Kill the Past", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Birthday Cake"), "{{Heart}} +1 HP#A random consumable and pickups of each type now spawn at the start of a floor#When the player holds Binge Eater,{{Speed}} -0.03 Speed and {{Tears}} +0.5 Tears", "Birthday Cake", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Rusty Spoon"), "#10% chance to fire a homing tear that inflicts {{BleedingOut}}bleed#100% chance at 18 {{Luck}}Luck", "Rusty Spoon", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Newgrounds Tank"), "{{Speed}}-0.3 Speed#{{Tears}}+0.27 Tears#{{Damage}}+0.5 Damage#{{Range}}+1 Range#{{Shotspeed}}+0.16 Shot Speed#{{Luck}}+1 Luck#On taking a hit, the player has a 10% chance to shield from damage", "Newgrounds Tank", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Greed Butt"), "#When hit by an enemy or projectile , you fart, launching a {{Coin}}coin out of your butt#There is a 5% chance that you drop a gold poop instead", "Greed Butt", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Focus"), "#When below full red hearts {{Heart}}, heal 1 red heart{{Heart}}#When at full health, launch a large piercing tear#This item only gains charge by inflicting damage", "Focus", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName(" Focus "), "#When below full red hearts {{Heart}}, heal 1 red heart{{Heart}}#When at full health, launch a large piercing tear#This item only gains charge by inflicting damage", "Focus", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("  Focus  "), "#When below full red hearts {{Heart}}, heal 1 red heart{{Heart}}#When at full health, launch a large piercing tear#This item only gains charge by inflicting damage", "Focus", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("   Focus   "), "#When below full red hearts {{Heart}}, heal 1 red heart{{Heart}}#When at full health, launch a large piercing tear#This item only gains charge by inflicting damage", "Focus", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("The Doorway"), "#All doors are opened, and stay open for the rest of the floor#{{SecretRoom}} Secret rooms, {{AngelRoom}} Angel/{{DevilRoom}} Devil rooms, The Mega Satan door, {{Timer}} Boss Rush and {{Hush}} Hush are included#{{ChallengeRoom}} Challenge Rooms are open to enter, however the door closes when activating the challenge#{{UltraSecretRoom}} The Ultra Secret Room is unlocked, and red rooms are now open to the edge of the map, revealing the {{ERROR}} error room", "The Doorway", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Strange Marble"), "#All enemies have a 1 in 8 chance to become champions#Champions always drop loot, and often have a chance to drop extra", "Strange Marble", "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Is You"), "#Point the reticle at an obstacle to use an active item effect that corresponds to it#Rock - Mom's Bracelet {{Collectible604}}#Pot/Fool's Gold - Wooden Nickel {{Collectible349}}#Poop - The Poop {{Collectible36}}", "Is You",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Nightmare Tick"), "#Every 8 room clears, one passive item is removed from your inventory#{{Damage}} +0.75 Damage for each item removed this way", "Nightmare Tick",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Spelunker's Pack"), "#+12 {{Bomb}} bombs#Bombs are Throwable now#(Effect below is the second effect that can be turned on in configuration)#Pits within your bombs' blast radius are filled in#When your bomb explodes, the resonant force breaks tinted and super secret rocks throughout the room #Bomb rocks in the room will break apart, dropping a {{Bomb}} bomb pickup", "Spelunker's Pack",  "en_us")

    EID:addTrinket(Isaac.GetTrinketIdByName("Ring of the Snake"), "#Receive 2 {{Card}} cards at the start of each floor", "Ring of the Snake", "en_us")

    EID:addCollectible(Isaac.GetItemIdByName("Diogenes's Pot"), "Toggles a melee hammer strike on and off#When equipped, you receive a {{Damage}} 1.5x damage multiplier# {{Card1}} Getting hit while equipped teleports you to the starting room", "Diogenes's Pot",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName(" Diogenes's Pot "), "Toggles a melee hammer strike on and off#When equipped, you receive a {{Damage}} 1.5x damage multiplier# {{Card1}} Getting hit while equipped teleports you to the starting room", "Diogenes's Pot",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("George"), "{{Range}} +2.4 Range#When entering most special rooms, a red room will unlock across from you", "George",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Possession"), "Each room, one random non-boss enemy will be permanently {{Charm}} charmed#These enemies carry over between rooms#Only 15 enemies can be {{Charm}} charmed at a time#Taking damage (excluding sacrifice rooms, etc) removes the charm from all affected enemies, making them hostile again#Stackable", "Possession",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Lollipop"), "Spawns a lollipop orbital. It does no damage, but it {{Charm}} charms enemies on contact#This orbital blocks bullets and breaks over time#When Lollipop breaks, Spawn a {{Heart}} Heart", "Lollipop",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("   Water Bottle   "), "I did not hit her#It is bullshit#I did not hit her#I did not", "Water Bottle",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("  Water Bottle  "), "{{Tears}} +0.22 Tears#{{Tearsize}} Tear Size Up", "Water Bottle",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName(" Water Bottle "), "{{Tears}} +0.37 Tears#{{Tearsize}} Tear Size Up", "Water Bottle",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Water Bottle"), "{{Tears}} +0.43 Tears#{{Tearsize}} Tear Size Up", "Water Bottle",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Aubrey"), "Once per floor, when entering a shop, a weapon beggar will spawn.#Weapon beggars take {{Coin}} coins, and spawn only {{Collectible}} active items from every pool.#3 {{Collectible}} active items are spawned from one weapon beggar before it leaves.", "Aubrey",  "en_us")

    EID:addCollectible(Isaac.GetItemIdByName("Tony"), "{{Damage}} +1.7 Damage Multiplier#{{Damage}} +1 Damage#{{ArrowDown}} When any {{Collectible}}item is taken, the buff and multiplier are both reduced by 0.1#This item's minimum damage multiplier is 1, it cannot decrease damage", "Tony",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("The Real Left Hand"), "On use, upgrades all {{Chest}} chests in the room into a better counterpart#Chest Order: {{SpikedChest}} Mimic -> {{HauntedChest}} Haunted -> {{Chest}} Grey -> {{RedChest}} Red -> {{GoldenChest}} Golden or {{StoneChest}} Stone -> {{WoodenChest}} Wooden or {{DirtyChest}} Old -> {{HolyChest}} Eternal -> {{MegaChest}} Mega", "The Real Left Hand",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Hitops"), "{{Speed}} +0.2 Speed#This speed up can exceed the speed cap", "Hitops",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Pop Pop"), "Double tap to fire two 3x damage tears in a burst#{{Timer}} Tear rate is reduced for a short time after using this effect.", "Pop Pop",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Football"), "{{Throwable}} Spawns a football familiar that can be picked up and thrown at enemies#The football deals {{Damage}} damage based on its speed", "Football",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Ball of Tumors"), "{{Bomb}} Bombs, {{Heart}} hearts, {{Key}} keys and {{Battery}} batteries have a small chance of turning into collectible tumors#Collecting tumors powers a tumor orbital, which blocks shots and deals contact damage#With enough tumors, a second orbital will spawn", "Ball of Tumors",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Bow and Arrow"), "Isaac is able to shoot small, piercing arrow tears that deal 2.5x {{Damage}} damage, capacity depends on your tear rate#Once the ammo is depleted, Isaac fires normal tears#When a tear lands, it drops an arrow that will replenish 1 tear when collected", "Bow and Arrow",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Emergency Meeting"), "{{Card1}} On use, teleports you and all other enemies in the room to the starting room.#On arrival, all enemies, including bosses, are confused for a few seconds", "Emergency Meeting",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Boxing Glove"), "{{Chargeable}} Gain a charged punching attack with a {{Timer}} 2.35 second charge time#The punch has high knockback and {{Confusion}} stuns enemies", "Boxing Glove",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Gravity"), "On use, you fall up to the ceiling for about {{Timer}} 5 seconds.#While in this state, gain {{Seraphim}} flight, invulnerability, and {{Range}} +6.25 Range#Tears rain down from the top of the screen, regardless of the fired direction.", "Gravity",  "en_us")
    EID:addCollectible( Isaac.GetItemIdByName("Johnny's Knives"), "{{Throwable}} Gain two homing flying knife familiars that do damage on contact#When killing enemies with the knives, spawn a pool of red creep that damages enemies. The size of the creep depends on the enemy's mass.#When enemy is killed by knives, gain {{Tears}} +0.5 Tears to the rest of the room.", "Johnny's Knives",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Ser Junkan"), "Spawns a familiar that pursues enemies and does contact damage.#You can blow up items with bombs. Collecting the junk that comes out upgrades your familiar.#Collecting 7 junk gives Junkan flight, and lets him fire spectral homing projectiles at the nearest enemy.", "Ser Junkan",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("The Crowdfunder"), "Press the drop button to toggle a coin-firing minigun#Each bullet costs 1 cent to fire.#When hitting a wall, bullets have a chance to drop a fading coin.#Killing enemies with The Crowdfunder may also drop extra money.", "The Crowdfunder",  "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Polar Star"), "TOADD" "Polar Star" "en_us")
    EID:addCollectible(Isaac.GetItemIdByName("Booster V2.0"), "TOADD" "Booster V2.0" "en_us")
	
    EID:addTrinket(Isaac.GetTrinketIdByName("Hunky Boys"), "While held, pressing the Drop Trinket button immediately drops this trinket; you don't need to hold the button#When on the ground, enemies will target the trinket for a short time.", "Hunky Boys", "en_us")
    EID:addTrinket(Isaac.GetTrinketIdByName("Bible Thump"), "{{Collectible33}} The Bible is added to several item pools.#Using {{Collectible33}} The Bible or {{Card71}} The Devil? card with this item will deal 40 damage to all enemies in the room, in addition to granting flight.#Using The Bible on {{Satan}} Satan will kill him, and you will survive#The golden version of this trinket kills {{TheLamb}} The Lamb as well.", "Bible Thump", "en_us")
    EID:addTrinket(Isaac.GetTrinketIdByName("Cheep Cheep"), "On entering a room, a random enemy is targeted by other enemies and has a {{Fear}} fear effect for 3 seconds.#If the effect is golden, the target also bleeds.", "Cheep Cheep", "en_us")

    EID:addCard(Isaac.GetCardIdByName("CowOnTrash"), "Rerolls all items into {{LordoftheFlies}} fly themed items#Rerolls pickups into blue flies#Does not actually become back your {{Coin}} money", "Cow on a Trash Farm", "en_us")
    EID:addCard(Isaac.GetCardIdByName("LootCard"), "Randomly spawns a random {{Collectible}} item or {{Trinket}} trinket from any pool", "Loot Card", "en_us")
    EID:addCard(Isaac.GetCardIdByName("Blank"), "Clears all enemy projectiles in the room.#Pushes nearby enemies away#There is one use left", "Blank", "en_us")
    EID:addCard(Isaac.GetCardIdByName("Blank2"), "Clears all enemy projectiles in the room.#Pushes nearby enemies away#There are two uses left", "Blank", "en_us")
    EID:addCard(Isaac.GetCardIdByName("Blank3"), "Clears all enemy projectiles in the room.#Pushes nearby enemies away#You can use this 3 times before it disappears", "Blank", "en_us")
    EID:addCard(Isaac.GetCardIdByName("JesterCube"), "On use, all {{Collectible}} items in the room will cycle between 6 additional choices, similar to Glitched Crown", "Jester", "en_us")
    EID:addCard(Isaac.GetCardIdByName("WitchCube"), "50% chance to deal 40 damage to all enemies in the room and apply burn.#50% chance to spawn another Witch and fire off a poison fart", "Witch", "en_us")
    EID:addCard(Isaac.GetCardIdByName("MurderCard"), "For a quarter second, increase speed to 4 and kill everything you touch.#Gain a {{Stompy}} Stompy effect for the room", "Murder!", "en_us")
    EID:addCard(Isaac.GetCardIdByName("AmberChunk"), "All pickups in the room, including {{Collectible}} items and the final chest at the end of the game, will be removed and saved.#The previous items you consumed in this way will respawn, even across games#You will also receive a {{Coin}} lucky penny", "Chunk of Amber", "en_us")
    EID:addCard(Isaac.GetCardIdByName("FiendFire"), "All pickups in the room are consumed#For each pickup consumed, gain a small, permanent boost to {{Damage}} Damage, {{Tears}} Tears, {{Luck}} Luck, {{Range}} Range, or {{Speed}} Speed#Pickups turn into {{Burning}} fires, which can damage enemies.", "Fiend Fire", "en_us")
    EID:addCard(Isaac.GetCardIdByName("DemonForm"), "For the current room, Isaac becomes {{Player7}} Azazel with a wide Brimstone#{{Damage}} +1 Damage", "Demon Form", "en_us")
    
    local CardHuds = {}
    CardHuds.CowHud = Sprite()
    CardHuds.CowHud:Load("gfx/cards_1_cow_on_trash.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_COW_TRASH_FARM), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.CowHud)
    CardHuds.LootCard = Sprite()
    CardHuds.LootCard:Load("gfx/cards_2_lootcard.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_LOOT_CARD), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.LootCard)
    CardHuds.Blank1 = Sprite()
    CardHuds.Blank1:Load("gfx/cards_3_blank.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_BLANK), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Blank1)
    CardHuds.Blank2 = Sprite()
    CardHuds.Blank2:Load("gfx/cards_3.1_blank.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_BLANK_2), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Blank2)
    CardHuds.Blank3 = Sprite()
    CardHuds.Blank3:Load("gfx/cards_3.2_blank.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_BLANK_3), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Blank3)
    CardHuds.Jester = Sprite()
    CardHuds.Jester:Load("gfx/cards_4_jestercube.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_JESTER_CUBE), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Jester)
    CardHuds.Witch = Sprite()
    CardHuds.Witch:Load("gfx/cards_5_witchcube.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_WITCH_CUBE), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Witch)
    CardHuds.Murder = Sprite()
    CardHuds.Murder:Load("gfx/cards_6_murdercard.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_MURDER), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.Murder)
    CardHuds.AmberChunk = Sprite()
    CardHuds.AmberChunk:Load("gfx/cards_7_amberchunk.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_AMBER_CHUNK), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.AmberChunk)
    CardHuds.DemonForm = Sprite()
    CardHuds.DemonForm:Load("gfx/cards_8_slaycard.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_DEMON_FORM), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.DemonForm)
    CardHuds.FiendFire = Sprite()
    CardHuds.FiendFire:Load("gfx/cards_8_slaycard.anm2", true)
    EID:addIcon("Card" .. tostring(WarpZone.WarpZoneTypes.CARD_FIEND_FIRE), "HUDSmall", 0, 16, 16, 6, 6, CardHuds.FiendFire)


    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_GOLDENIDOL, "Зачистка комнаты имеет 50% шанс оставить никель, пропадающий через 2 секунды.#При получении урона игрок теряет половину своих монет, и бросает на пол эти монеты (они пропадают через 1 секунду).#Если у игрока есть монеты, урон будет в полное сердце.", "Золотой Идол", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_PASTKILLER, "Удаляет первые три предмета,полученных в забеге (Может удалить сюжетные предметы).#Создает по три пьедестала с предметами из того же пула за каждый потерянный предмет, из 3х предметов можно взять только 1.#The new items are from the same pools as the ones you lost.", "Пушка, Убивающая Прошлое", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_PASTKILLER_2x, "Удаляет первые три предмета,полученных в забеге (Может удалить сюжетные предметы).#Создает по три пьедестала с предметами из того же пула за каждый потерянный предмет, из 3х предметов можно взять только 1.#The new items are from the same pools as the ones you lost.", "Пушка, Убивающая Прошлое", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_PASTKILLER_1x, "Удаляет первые три предмета,полученных в забеге (Может удалить сюжетные предметы).#Создает по три пьедестала с предметами из того же пула за каждый потерянный предмет, из 3х предметов можно взять только 1.#The new items are from the same pools as the ones you lost.", "Пушка, Убивающая Прошлое", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_BIRTHDAY_CAKE, "{{ArrowUp}} +1 Контейнер Сердца #Случайная карта/пилюля/руна, случайная монета, бомба и ключ появляются в начале каждого этажа.#Предмет еды, С Кутежником дает -.03 скорости и +.5 скорострельности.", "Именинный Торт", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_RUSTY_SPOON, "10% шанс выстрелить самонаводящейся слезой, накладывающей кровотечение#100% шанс при 18 удачи", "Ржавая Ложка", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_NEWGROUNDS_TANK, "{{ArrowDown}}  -.3 Скорости#{{ArrowUp}} +.27 Скорострельности#{{ArrowUp}} +.5 Урона#{{ArrowUp}} +.04 Дальности#{{ArrowUp}} +.16 Скорости слезы#{{ArrowUp}} +1 Удачи#При получении урона, 10% шанс предотвратить его.", "Танк Newgrounds", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_GREED_BUTT, "При получении урона в зад, персонаж пукает и выпускает монетку.#4% шанс создать золотую кучку вместо пука с монетой.", "Алчная Жопа!", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_FOCUS, "Если у вас не полное здоровье, вылечи 1 красное сердце.#При полном здоровье, выпусти большую слезу, наносящую большой урон, проходящую сквозь врагов.#Этот предмет заряжается нанесением урона.", "Фокус", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_FOCUS_2, "Если у вас не полное здоровье, вылечи 1 красное сердце.#При полном здоровье, выпусти большую слезу, наносящую большой урон, проходящую сквозь врагов.#Этот предмет заряжается нанесением урона", "Фокус", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_FOCUS_3, "Если у вас не полное здоровье, вылечи 1 красное сердце.#При полном здоровье, выпусти большую слезу, наносящую большой урон, проходящую сквозь врагов.#Этот предмет заряжается нанесением урона", "Фокус", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_FOCUS_4, "Если у вас не полное здоровье, вылечи 1 красное сердце.#При полном здоровье, выпусти большую слезу, наносящую большой урон, проходящую сквозь врагов.#Этот предмет заряжается нанесением урона", "Фокус", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_DOORWAY, "Все двери открываются, и остаются открытыми до конца этажа.#Открываются Секретные комнаты, комнаты Ангела/Дьявола, Дверь Мега Сатаны, Двери Испытания Боссов и Молчания (Если они на этом этаже).#Комнаты испытания открыты, но дверь закрывается на время прохождения испытания.#Открывает Ультра Секретную комнату и проход к ней, так же открывает проход к комнате Ошибки, открывая красные комнаты через Ультра секретную комнату до края карты.", "Проход", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_STRANGE_MARBLE, "Все враги с 10% шансом могут стать чемпионами.#Чемпионы всегда оставляют награду, и могут оставить дополнительную.", "Странный Марбл", "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_IS_YOU, "Создает крестик под персонажем, который надо направлять на препятствия (Камни, Блоки и т.д.).#После этого, нужно еще раз активировать предмет для срабатывания эффекта. У каждого обьекта свой эффект.", "Это Ты",  "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_NIGHTMARE_TICK, "Каждые 8 зачисток комнат, Один предмет пропадает из инвентаря.#+.75 Урона за пропавший предмет", "Кошмарный Клещ",  "ru")
    EID:addCollectible(WarpZone.WarpZoneTypes.COLLECTIBLE_SPELUNKERS_PACK, "+12 бомб#Все ямы в радиусе взрыва заполняются.#При взрыве бомбы, Все меченые и двойные меченые камни взорвутся не смотря на то что они вне радиуса взрыва. #Камни с бомбами сломаются и оставят бомбу на их месте.", "Рюкзак Спелеолога",  "ru")

end
